# Generated by Django 4.2.4 on 2024-02-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
